/* Starter recipes so The Breadboard isn't an empty box on first launch.
   No photos bundled — each falls back to its type illustration until
   you add your own. Edit or delete any of these freely. */

const SEED_RECIPES = [
  {
    id: 'seed-sourdough-boule',
    title: 'Classic Sourdough Boule',
    type: 'sourdough',
    difficulty: 'Medium',
    favourite: true,
    createdAt: Date.now() - 6 * 86400000,
    prep: 30, prove: 360, bake: 45,
    hydration: 75,
    yieldText: '1 large 900g boule',
    ovenTemp: '250°C (230°C fan) · Dutch oven',
    tags: ['sourdough', 'weekend bake', 'crusty'],
    images: [],
    ingredientGroups: [
      { heading: 'Levain', items: ['50g active sourdough starter', '100g strong white bread flour', '100g water, room temp'] },
      { heading: 'Dough', items: ['500g strong white bread flour', '375g water, warm', '200g ripe levain (from above)', '10g fine sea salt'] },
    ],
    methodGroups: [
      { heading: 'Build the levain', items: ['The night before, mix starter, flour and water in a jar. Cover loosely and leave at room temperature 8–12 hours until doubled and domed.'] },
      { heading: 'Mix & autolyse', items: ['Combine flour and 350g of the water. Mix to a shaggy dough, cover and rest 30–60 minutes.', 'Add the levain and remaining 25g water. Pinch and fold to combine.', 'Sprinkle over the salt and work it in with wet hands until fully incorporated.'] },
      { heading: 'Bulk ferment', items: ['Perform 4 sets of stretch-and-folds, 30 minutes apart.', 'Bulk ferment at warm room temperature (24–26°C) for 3–4 hours, until risen by about 50% and jiggly.'] },
      { heading: 'Shape & prove', items: ['Turn out, pre-shape into a round and rest 20 minutes.', 'Shape into a tight boule and place seam-side up in a floured banneton.', 'Cover and refrigerate 8–12 hours (overnight).'] },
      { heading: 'Bake', items: ['Preheat oven with a Dutch oven inside to 250°C for 45 minutes.', 'Turn the loaf onto parchment, score decisively with a lame.', 'Bake covered 20 minutes, then uncovered at 230°C a further 20–25 minutes until deeply golden.', 'Cool on a wire rack at least 1 hour before slicing.'] },
    ],
    notes: 'Starter should double within 6 hours of feeding before you build the levain. If your kitchen is cool, extend bulk fermentation rather than the clock.',
  },
  {
    id: 'seed-focaccia',
    title: 'Rustic Focaccia al Rosmarino',
    type: 'yeasted',
    difficulty: 'Easy',
    favourite: false,
    createdAt: Date.now() - 5 * 86400000,
    prep: 20, prove: 150, bake: 25,
    hydration: 80,
    yieldText: '1 tray, 20×30cm',
    ovenTemp: '220°C (200°C fan)',
    tags: ['focaccia', 'olive oil', 'rosemary', 'easy'],
    images: [],
    ingredientGroups: [
      { heading: 'Dough', items: ["500g '00' or strong white flour", '400g warm water', '10g fine sea salt', '7g fast-action dried yeast', '60ml extra virgin olive oil, plus extra for the tin'] },
      { heading: 'Topping', items: ['Flaky sea salt', '2 sprigs rosemary, needles picked', 'Extra virgin olive oil, for drizzling'] },
    ],
    methodGroups: [
      { heading: 'Mix', items: ['Whisk yeast into the warm water and leave 5 minutes.', 'Combine flour and salt, pour in the yeasted water and olive oil. Mix to a very wet, shaggy dough.'] },
      { heading: 'Bulk & fold', items: ['Cover and rest 20 minutes, then do 3 sets of stretch-and-folds in the bowl, 20 minutes apart.', 'Leave to rise until roughly doubled, about 1.5 hours.'] },
      { heading: 'Pan & dimple', items: ['Pour a generous glug of olive oil into a baking tray. Tip the dough in and stretch gently to the edges.', 'Cover and rest 30–40 minutes until puffy.', 'Dimple all over with oiled fingers, right down to the tray.'] },
      { heading: 'Bake', items: ['Scatter with rosemary and flaky salt, drizzle with more oil.', 'Bake at 220°C for 22–25 minutes until deep golden and crisp at the edges.', 'Drizzle with a little more oil straight out of the oven.'] },
    ],
    notes: "Don't be afraid of the wet dough — a slack dough is what gives focaccia its open, pillowy crumb.",
  },
  {
    id: 'seed-baguette',
    title: 'Baguette de Tradition',
    type: 'yeasted',
    difficulty: 'Hard',
    favourite: false,
    createdAt: Date.now() - 4 * 86400000,
    prep: 30, prove: 180, bake: 22,
    hydration: 70,
    yieldText: '3 baguettes',
    ovenTemp: '240°C (220°C fan) · steam',
    tags: ['baguette', 'french', 'lean dough'],
    images: [],
    ingredientGroups: [
      { heading: 'Dough', items: ['500g T65 or strong white flour', '350g water, cool', '10g fine sea salt', '4g fresh yeast (or 1.5g dried)'] },
    ],
    methodGroups: [
      { heading: 'Mix & bulk', items: ['Mix flour, water and yeast to a rough dough, rest 20 minutes (autolyse).', 'Add salt, mix until smooth and elastic, about 8 minutes by hand.', 'Bulk ferment 2 hours at room temperature with a fold every 30 minutes.'] },
      { heading: 'Divide & shape', items: ['Divide into 3 × 280g pieces. Pre-shape into logs and rest 20 minutes.', 'Shape into baguettes, building tension along the length.'] },
      { heading: 'Prove & score', items: ['Prove seam-side up in a floured couche for 45–60 minutes.', 'Transfer to a peel, score with 4–5 confident overlapping slashes.'] },
      { heading: 'Bake', items: ['Bake at 240°C with steam for 10 minutes, then vent and drop to 220°C a further 10–12 minutes until deeply blistered.'] },
    ],
    notes: 'Steam in the first 10 minutes gives the shatter-crisp crust — a tray of ice cubes on the oven floor works well at home.',
  },
  {
    id: 'seed-rye',
    title: '90% Dark Rye Loaf',
    type: 'rye',
    difficulty: 'Medium',
    favourite: false,
    createdAt: Date.now() - 3 * 86400000,
    prep: 20, prove: 120, bake: 60,
    hydration: 85,
    yieldText: '1 × 900g tin loaf',
    ovenTemp: '230°C, then 200°C',
    tags: ['rye', 'wholegrain', 'dense', 'sourdough'],
    images: [],
    ingredientGroups: [
      { heading: 'Rye sour', items: ['80g rye starter', '160g dark rye flour', '160g water'] },
      { heading: 'Dough', items: ['All of the rye sour', '270g dark rye flour', '30g strong white flour', '290g water, warm', '10g fine sea salt', '20g blackstrap molasses', 'Handful cracked rye or seeds, optional'] },
    ],
    methodGroups: [
      { heading: 'Build the sour', items: ['Mix rye sour ingredients the evening before and leave at room temperature 10–12 hours.'] },
      { heading: 'Mix', items: ['Combine all dough ingredients into a thick, sticky batter-like dough — it will not look like a wheat dough, and that’s correct.', 'Beat well with a spatula for a minute to develop structure.'] },
      { heading: 'Prove', items: ['Scrape into a well-greased and lined 900g loaf tin, smooth the top with a wet hand.', 'Cover and prove until risen by about half with small cracks on the surface, 2–3 hours.'] },
      { heading: 'Bake', items: ['Bake at 230°C for 15 minutes, then reduce to 200°C and bake a further 45 minutes.', 'Turn out and tap the base — it should sound hollow. Wrap in a tea towel and cool completely (ideally overnight) before slicing.'] },
    ],
    notes: 'Rye loaves slice best the next day once the crumb has fully set — resist cutting it warm.',
  },
  {
    id: 'seed-brioche',
    title: 'Brioche Nanterre',
    type: 'enriched',
    difficulty: 'Hard',
    favourite: false,
    createdAt: Date.now() - 2 * 86400000,
    prep: 30, prove: 240, bake: 35,
    hydration: 55,
    yieldText: '1 × 900g tin loaf',
    ovenTemp: '180°C (160°C fan)',
    tags: ['brioche', 'enriched', 'buttery', 'breakfast'],
    images: [],
    ingredientGroups: [
      { heading: 'Dough', items: ['500g strong white flour', '60g caster sugar', '10g fine sea salt', '10g fast-action dried yeast', '6 medium eggs', '80g whole milk', '250g unsalted butter, soft, cubed'] },
      { heading: 'To finish', items: ['1 egg, beaten, for egg wash'] },
    ],
    methodGroups: [
      { heading: 'Mix', items: ['Combine flour, sugar, salt and yeast (keep salt and yeast apart initially).', 'Add eggs and milk, mix to a smooth dough, about 10 minutes on medium in a stand mixer.', 'Add butter a few cubes at a time, mixing until fully incorporated and the dough is glossy and elastic — 10–15 minutes.'] },
      { heading: 'Chill', items: ['Cover and chill overnight — this dough is too soft to shape at room temperature.'] },
      { heading: 'Shape & prove', items: ['Divide into 8 even balls, arrange in two rows in a lined loaf tin.', 'Cover and prove at room temperature until puffy and doubled, about 2–3 hours.'] },
      { heading: 'Bake', items: ['Brush with egg wash.', 'Bake at 180°C for 30–35 minutes, tenting with foil if it colours too quickly.', 'Cool in the tin 10 minutes, then turn out onto a rack.'] },
    ],
    notes: 'Keep the dough cold while shaping — warm brioche dough is unworkably sticky.',
  },
  {
    id: 'seed-flatbread',
    title: 'Soft Everyday Flatbread',
    type: 'flatbread',
    difficulty: 'Easy',
    favourite: false,
    createdAt: Date.now() - 1 * 86400000,
    prep: 15, prove: 60, bake: 6,
    hydration: 65,
    yieldText: '8 flatbreads',
    ovenTemp: 'Hot dry pan or grill',
    tags: ['flatbread', 'quick', 'yogurt', 'no special equipment'],
    images: [],
    ingredientGroups: [
      { heading: 'Dough', items: ['500g plain or strong flour', '7g fast-action dried yeast', '1 tsp sugar', '200g natural yogurt', '120g warm water', '2 tbsp olive oil', '8g fine sea salt'] },
    ],
    methodGroups: [
      { heading: 'Mix & rise', items: ['Whisk yeast, sugar and warm water, leave 5 minutes.', 'Combine flour and salt, add yogurt, oil and the yeast mixture. Mix and knead to a soft, smooth dough, 6–8 minutes.', 'Cover and rise until doubled, about 1 hour.'] },
      { heading: 'Cook', items: ['Divide into 8 pieces, roll each into a thin oval.', 'Cook in a very hot dry pan or under a hot grill, 60–90 seconds per side, until puffed and charred in spots.', 'Stack under a clean tea towel to keep soft while you cook the rest.'] },
    ],
    notes: 'Brush with melted butter and garlic straight off the pan for a naan-style finish.',
  },
];
