/* Recipe Box — recipe data
   Each recipe: id, title, category, emoji, source url + name, time, servings,
   ingredients (array of strings, or array of {heading, items} for multi-part recipes),
   method (array of strings, or array of {heading, steps} for multi-part recipes),
   status: 'pending' (not yet transcribed) | 'ready' (full method available)
*/
const RECIPES = [
  {
    id: 'chickpea-traybake',
    title: 'Chickpea & Veg Traybake',
    category: 'Mains',
    emoji: '🥘',
    source: 'https://plantbasednews.org/wprm_print/chickpea-traybake',
    sourceName: 'Plant Based News',
    time: '',
    servings: '',
    ingredients: [],
    method: [],
    status: 'pending'
  },
  {
    id: 'crispy-tofu',
    title: 'Crispy Tofu',
    category: 'Mains',
    emoji: '🍱',
    source: 'https://www.bbcgoodfood.com/recipes/crispy-tofu',
    sourceName: 'BBC Good Food',
    time: '',
    servings: '',
    ingredients: [],
    method: [],
    status: 'pending'
  },
  {
    id: 'falafel',
    title: 'Falafel',
    category: 'Mains',
    emoji: '🧆',
    source: 'https://www.loveandlemons.com/wprm_print/42582',
    sourceName: 'Love and Lemons',
    time: '',
    servings: '',
    ingredients: [],
    method: [],
    status: 'pending'
  },
  {
    id: 'harissa-tofu-flatbreads',
    title: 'Harissa Tofu Flatbreads & Butterbean Hummus',
    category: 'Mains',
    emoji: '🌯',
    source: 'https://www.rebelrecipes.com/harissa-tofu-flatbreads-with-creamy-butterbean-hummus/',
    sourceName: 'Rebel Recipes',
    time: '',
    servings: '',
    ingredients: [],
    method: [],
    status: 'pending'
  },
  {
    id: 'black-bean-stew',
    title: 'Black Bean Stew',
    category: 'Mains',
    emoji: '🍲',
    source: 'https://makeitdairyfree.com/vegan-black-bean-stew/',
    sourceName: 'Make It Dairy Free',
    time: '',
    servings: '',
    ingredients: [],
    method: [],
    status: 'pending'
  },
  {
    id: 'pita-bread',
    title: 'Pita Bread',
    category: 'Bakery',
    emoji: '🫓',
    source: 'https://myfoodstory.com/wprm_print/36376',
    sourceName: 'My Food Story',
    time: '',
    servings: '',
    ingredients: [],
    method: [],
    status: 'pending'
  },
  {
    id: 'seeded-crackers',
    title: 'Seeded Crackers',
    category: 'Snacks & Dips',
    emoji: '🍘',
    source: 'https://plantbaes.com/healthy-seeded-crackers/',
    sourceName: 'Plantbaes',
    time: '',
    servings: '',
    ingredients: [],
    method: [],
    status: 'pending'
  },
  {
    id: 'hummus',
    title: 'Hummus',
    category: 'Snacks & Dips',
    emoji: '🥣',
    source: 'https://www.loveandlemons.com/hummus-recipe/',
    sourceName: 'Love and Lemons',
    time: '',
    servings: '',
    ingredients: [],
    method: [],
    status: 'pending'
  },
  {
    id: 'almond-bread',
    title: 'Almond Flour Bread',
    category: 'Bakery',
    emoji: '🍞',
    source: 'https://healthyrecipesblogs.com/gluten-free-bread/',
    sourceName: 'Healthy Recipes Blogs',
    time: '',
    servings: '',
    ingredients: [],
    method: [],
    status: 'pending'
  },
  {
    id: 'chickpea-crackers',
    title: 'Chickpea Crackers',
    category: 'Snacks & Dips',
    emoji: '🧂',
    source: 'https://ohmyveggies.com/wprm_print/76043',
    sourceName: 'Oh My Veggies',
    time: '',
    servings: '',
    ingredients: [],
    method: [],
    status: 'pending'
  },
  {
    id: 'boars-head-hummus',
    title: 'Sweet Chili Garlic Hummus',
    category: 'Snacks & Dips',
    emoji: '🌶️',
    source: 'https://shaneandsimple.com/boars-head-sweet-chili-garlic-hummus-copycat/',
    sourceName: 'Shane & Simple',
    time: '',
    servings: '',
    ingredients: [],
    method: [],
    status: 'pending'
  },
  {
    id: 'sourdough-dinner-rolls',
    title: 'Sourdough Dinner Rolls',
    category: 'Bakery',
    emoji: '🥐',
    source: 'https://vm.tiktok.com/ZGdkUnr7E/',
    sourceName: 'TikTok',
    time: '',
    servings: '',
    ingredients: [],
    method: [],
    status: 'pending'
  },
  {
    id: 'rye-sourdough',
    title: 'Rye Sourdough Bread',
    category: 'Bakery',
    emoji: '🍞',
    source: 'https://heartbeetkitchen.com/rye-sourdough-bread-recipe/',
    sourceName: 'Heartbeet Kitchen',
    time: '',
    servings: '',
    ingredients: [],
    method: [],
    status: 'pending',
    note: 'A dedicated bake-day companion app with a dough temperature calculator for this recipe is also available.',
    companionApp: '../Rye/index.html'
  },
  {
    id: 'sourdough-crackers',
    title: 'Sourdough Crackers',
    category: 'Snacks & Dips',
    emoji: '🍪',
    source: 'https://www.kingarthurbaking.com/recipes/sourdough-crackers-recipe',
    sourceName: 'King Arthur Baking',
    time: '',
    servings: '',
    ingredients: [],
    method: [],
    status: 'pending'
  },
  {
    id: 'lentil-bolognese',
    title: 'Lentil Spaghetti Bolognese',
    category: 'Mains',
    emoji: '🍝',
    source: 'https://rainbowplantlife.com/wprm_print/lentil-bolognese',
    sourceName: 'Rainbow Plant Life',
    time: '',
    servings: '',
    ingredients: [],
    method: [],
    status: 'pending'
  },
  {
    id: 'chickpea-meatballs',
    title: 'Chickpea Meatballs',
    category: 'Mains',
    emoji: '🍡',
    source: 'https://dishingouthealth.com/wprm_print/10105/',
    sourceName: 'Dishing Out Health',
    time: '',
    servings: '',
    ingredients: [],
    method: [],
    status: 'pending'
  },
  {
    id: 'wholewheat-wraps',
    title: 'Wholewheat Wraps',
    category: 'Bakery',
    emoji: '🌮',
    source: 'https://www.theleangreenbean.com/homemade-whole-wheat-tortillas/',
    sourceName: 'The Lean Green Bean',
    time: '',
    servings: '',
    ingredients: [],
    method: [],
    status: 'pending'
  },
  {
    id: 'butter-bean-curry',
    title: 'Butter Bean Curry',
    category: 'Mains',
    emoji: '🍛',
    source: 'https://www.bbcgoodfood.com/recipes/butter-bean-curry',
    sourceName: 'BBC Good Food',
    time: '',
    servings: '',
    ingredients: [],
    method: [],
    status: 'pending'
  },
  {
    id: 'flapjacks',
    title: 'Almond Butter Flapjacks',
    category: 'Snacks & Dips',
    emoji: '🍫',
    source: 'https://www.cinnamonandkale.co.uk/wprm_print/almond-butter-flapjacks',
    sourceName: 'Cinnamon & Kale',
    time: '',
    servings: '',
    ingredients: [],
    method: [],
    status: 'pending'
  },
  {
    id: 'baguettes',
    title: 'Baguettes',
    category: 'Bakery',
    emoji: '🥖',
    source: 'https://lechefswife.com/baking-baguettes-for-beginners/',
    sourceName: "Le Chef's Wife",
    time: '',
    servings: '',
    ingredients: [],
    method: [],
    status: 'pending'
  }
];
